channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - altair=5.5.0 
  - vegafusion=2.0.2
  - pyreadr=0.5.3
  - seaborn=0.13.2
  - matplotlib=3.10.0
  - pandas=2.2.3
  - pyarrow=20.0.0
  - click=8.1.8
  - pip
  - pip:
    - altair-ally==0.1.1
